services:
  postgres:
    image: postgres:16
    container_name: 'java-postgres'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  app:
#    build: /
    image: "l2ilai/spring-app:latest"
    container_name: 'java-app'
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
      SSH_IP: ${SSH_IP}
      SSH_KEY_PATH: ${SSH_KEY_PATH:-/id_rsa}
      SSH_USER: ${SSH_USER}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
    depends_on:
      - postgres
    ports:
      - 999:999
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
