services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: 'java-postgres'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: postgres
  app:
    image: "l2ilai/spring-app:latest"
    container_name: 'java-app'
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - 999:999


