server:
  port: 999
ssh-server:
  ip: ${SSH_IP}
  port: ${SSH_PORT:22}
  user: ${SSH_USER}
  pathToPrivateKey: ${SSH_KEY:C:\Users\Asakura\.ssh\id_rsa}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update